import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {visitors,taipeiDay,cleanup} from './visitors.mjs';
const origin='https://wackyjazz.github.io';
function fixture(){const db=new DatabaseSync(':memory:');db.exec(readFileSync(new URL('./visitors.sql',import.meta.url),'utf8'));const prepare=sql=>({bind(...args){return {sql,args,first:async()=>db.prepare(sql).get(...args),run:async()=>db.prepare(sql).run(...args)}}});return {db,env:{VISITORS:{prepare,batch:async statements=>{db.exec('BEGIN');try{const result=statements.map(({sql,args})=>({results:sql.startsWith('SELECT')?db.prepare(sql).all(...args):(db.prepare(sql).run(...args),[])}));db.exec('COMMIT');return result}catch(e){db.exec('ROLLBACK');throw e}}}}}}
const request=(id,headers={})=>new Request('https://example.com/api/visitors',{method:id?'POST':'GET',headers:{Origin:origin,'Content-Type':'text/plain',...headers},...(id?{body:id}:{})});
const id='11111111-1111-4111-8111-111111111111',id2='22222222-2222-4222-8222-222222222222';
test('Taipei midnight changes date, independent of UTC date',()=>{assert.equal(taipeiDay(new Date('2026-09-08T15:59:59Z')),'2026-09-08');assert.equal(taipeiDay(new Date('2026-09-08T16:00:00Z')),'2026-09-09')});
test('real SQL deduplicates simultaneous submissions and counts next day independently',async()=>{const {db,env}=fixture();try{const today=new Date('2026-09-08T10:00Z');await Promise.all(Array.from({length:20},()=>visitors(request(id),env,today)));let data=await (await visitors(request(),env,today)).json();assert.equal(data.visitors,1);assert.equal((await (await visitors(request(id2),env,today)).json()).visitors,2);assert.equal((await (await visitors(request(id),env,new Date('2026-09-08T16:00Z'))).json()).visitors,1);assert.equal(db.prepare('SELECT COUNT(*) n FROM daily_visitors').get().n,3)}finally{db.close()}});
test('foreign origins, invalid IDs and oversized bodies never write',async()=>{const {db,env}=fixture();try{assert.equal((await visitors(request(id,{Origin:'https://evil.example'}),env)).status,403);assert.equal((await visitors(request('fake'),env)).status,400);assert.equal((await visitors(request('a'.repeat(129)),env)).status,413);assert.equal((await visitors(request(id,{'Content-Type':'application/json'}),env)).status,415);assert.equal(db.prepare('SELECT COUNT(*) n FROM daily_visitors').get().n,0)}finally{db.close()}});
test('database outage returns unavailable instead of fake zero',async()=>{assert.equal((await visitors(request(),{VISITORS:{prepare(){throw Error('quota')}}})).status,503)});
test('cleanup removes old identifiers while preserving daily totals',async()=>{const {db,env}=fixture();try{await visitors(request(id),env,new Date('2026-09-01'));await visitors(request(id2),env,new Date('2026-09-08'));await cleanup(env,new Date('2026-09-08'));assert.equal(db.prepare('SELECT COUNT(*) n FROM daily_visitors').get().n,1);assert.equal(db.prepare('SELECT visitors FROM daily_totals WHERE day=?').get('2026-09-01').visitors,1)}finally{db.close()}});
